title: I'm learning!
author: Sugampret Jaya
email: djadoel97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sugampret Jaya is currently learning how to build his personal blog
  using Jekyll and GitHub repository. Wish me some joy and fun learning all these new things!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
